name: pxp-random-forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.7
  - numpy==2.4.2
  - pandas==2.3.1
  - matplotlib==3.10.0
  - jupyterlab==4.4.4
  - scikit-learn==1.6.1
  - seaborn==0.13.2
  - skimpy==0.0.18
  - pip==25.2

